### ISSUE TITLE
Replacing calls to the Buffer constructor in tests

### ISSUE THREAD

**Issue by gabrielschulhof** [watson/http-headers#4]
A call is made to the `Buffer` constructor [here](https://github.com/roytam1/basilisk55/issues/1), however, `new Buffer(...)` is deprecated and unsafe. A better alternative would be to use `Buffer.from(...)` instead. Would it be possible to update the code?

**Comment by mafintosh** [comment]
I don't see any buffers in this module at all?

**Comment by gabrielschulhof** [comment]
Sorry! Wrong link. It's in the [test](https://github.com/watson/http-headers/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22).

**Comment by mafintosh** [comment]
Tests are already using safe-buffer https://github.com/watson/http-headers/blob/08dcf111f788d8774dfe91516b50364e3e4940da/test.js#L5 ...

**Comment by gabrielschulhof** [comment]
Will it be safe to drop that dependency if we also switch to `Buffer.from()`?

**Comment by mafintosh** [comment]
It's already fine and not using any deprecated apis so no need for any changes that require a major bump. I think this can be closed.

**Comment by gabrielschulhof** [comment]
OK.

**Comment by watson** [comment]
@gabrielschulhof Check the docs for [safe-buffer](https://www.npmjs.com/package/safe-buffer). The `Buffer` exported from `safe-buffer` isn't the same `Buffer` that ships with Node core. It just has the same name but is designed to be safe (hence the name)

**Comment by gabrielschulhof** [comment]
@watson I know. I was just thinking that Node's `Buffer` is just fine, as long as you don't use the constructor – unless you also need support for older Node versions.

**Comment by watson** [comment]
For now the tests also runs on old versions of Node and since this is only used in the tests and not in production, I don't see a reason to bump the major version of the module just to get rid of a test dependency which doesn't cause any problems
